/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    programs: Program;
    'program-tags': ProgramTag;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'program-tags': ProgramTagsSelect<false> | ProgramTagsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'top-page': TopPage;
    'events-page': EventsPage;
    'sponsors-page': SponsorsPage;
    'weather-settings': WeatherSetting;
  };
  globalsSelect: {
    'top-page': TopPageSelect<false> | TopPageSelect<true>;
    'events-page': EventsPageSelect<false> | EventsPageSelect<true>;
    'sponsors-page': SponsorsPageSelect<false> | SponsorsPageSelect<true>;
    'weather-settings': WeatherSettingsSelect<false> | WeatherSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage users who can sign in to the admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manage images used on pages such as the top page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Used when image cannot be displayed or for screen readers.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Manage notices shown on the top and news pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  date: string;
  /**
   * Select “Important” to show this in the top-page important notice frame.
   */
  important: 'normal' | 'important';
  title: string;
  body: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage program information used on event pages and timetables.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  adminLabel?: string | null;
  title: string;
  category: 'program' | 'exhibition' | 'food' | 'goods' | 'corporate';
  area: 'lecture' | 'gym' | 'outdoor' | 'kitchen_car' | 'other';
  locationName: string;
  image?: (number | null) | Media;
  mapImage?: (number | null) | Media;
  tags?: (number | ProgramTag)[] | null;
  catchphrase?: string | null;
  /**
   * Enter visitor-facing information such as description, notes, requirements, ticketing, and rainy-day handling.
   */
  description: string;
  /**
   * Register schedule rows. Add separate rows when sunny and rainy schedules differ.
   */
  scheduleItems: {
    /**
     * Use Common for schedules shown in both sunny and rainy modes.
     */
    weather: 'both' | 'sunny' | 'rainy';
    day: 'day1' | 'day2';
    startTime:
      | '10:00'
      | '10:15'
      | '10:30'
      | '10:45'
      | '11:00'
      | '11:15'
      | '11:30'
      | '11:45'
      | '12:00'
      | '12:15'
      | '12:30'
      | '12:45'
      | '13:00'
      | '13:15'
      | '13:30'
      | '13:45'
      | '14:00'
      | '14:15'
      | '14:30'
      | '14:45'
      | '15:00'
      | '15:15'
      | '15:30'
      | '15:45'
      | '16:00'
      | '16:15'
      | '16:30'
      | '16:45'
      | '17:00'
      | '17:15'
      | '17:30'
      | '17:45'
      | '18:00'
      | '18:15'
      | '18:30'
      | '18:45'
      | '19:00'
      | '19:15'
      | '19:30'
      | '19:45'
      | '20:00'
      | '20:15'
      | '20:30';
    /**
     * Select when the program ends. It must be later than the start time.
     */
    endTime:
      | '10:00'
      | '10:15'
      | '10:30'
      | '10:45'
      | '11:00'
      | '11:15'
      | '11:30'
      | '11:45'
      | '12:00'
      | '12:15'
      | '12:30'
      | '12:45'
      | '13:00'
      | '13:15'
      | '13:30'
      | '13:45'
      | '14:00'
      | '14:15'
      | '14:30'
      | '14:45'
      | '15:00'
      | '15:15'
      | '15:30'
      | '15:45'
      | '16:00'
      | '16:15'
      | '16:30'
      | '16:45'
      | '17:00'
      | '17:15'
      | '17:30'
      | '17:45'
      | '18:00'
      | '18:15'
      | '18:30'
      | '18:45'
      | '19:00'
      | '19:15'
      | '19:30'
      | '19:45'
      | '20:00'
      | '20:15'
      | '20:30';
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage tags used for filtering programs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-tags".
 */
export interface ProgramTag {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'program-tags';
        value: number | ProgramTag;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  date?: T;
  important?: T;
  title?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  adminLabel?: T;
  title?: T;
  category?: T;
  area?: T;
  locationName?: T;
  image?: T;
  mapImage?: T;
  tags?: T;
  catchphrase?: T;
  description?: T;
  scheduleItems?:
    | T
    | {
        weather?: T;
        day?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "program-tags_select".
 */
export interface ProgramTagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure top-page sections such as pickup and news.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top-page".
 */
export interface TopPage {
  id: number;
  /**
   * Slides are displayed in order. Add as many as needed.
   */
  pickups?:
    | {
        image?: (number | null) | Media;
        /**
         * If empty, the image will not be clickable.
         */
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure program display order and visible tag order. Manage program publication from the Programs menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page".
 */
export interface EventsPage {
  id: number;
  /**
   * Drag rows to configure display order for program programs. Missing published programs are restored on save.
   */
  programItems?:
    | {
        /**
         * Select the program displayed by this row.
         */
        program?: (number | null) | Program;
        programLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Drag rows to configure display order for exhibition programs. Missing published programs are restored on save.
   */
  exhibitionItems?:
    | {
        /**
         * Select the program displayed by this row.
         */
        program?: (number | null) | Program;
        programLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Drag rows to configure display order for food programs. Missing published programs are restored on save.
   */
  foodItems?:
    | {
        /**
         * Select the program displayed by this row.
         */
        program?: (number | null) | Program;
        programLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Drag rows to configure display order for goods programs. Missing published programs are restored on save.
   */
  goodsItems?:
    | {
        /**
         * Select the program displayed by this row.
         */
        program?: (number | null) | Program;
        programLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Drag rows to configure display order for corporate programs. Missing published programs are restored on save.
   */
  corporateItems?:
    | {
        /**
         * Select the program displayed by this row.
         */
        program?: (number | null) | Program;
        programLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Configure visible tags and display order.
   */
  visibleTags?: (number | ProgramTag)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the thank-you message and sponsor list shown on the sponsors page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors-page".
 */
export interface SponsorsPage {
  id: number;
  /**
   * Shown under the sponsors page title. Line breaks are preserved.
   */
  thanksMessage: string;
  /**
   * Rows are displayed in order. Rows with images become ad cards; rows without images become name-only entries.
   */
  sponsors?:
    | {
        /**
         * Enter the official company name displayed on the page.
         */
        companyName: string;
        /**
         * If set, this sponsor is shown as an ad card. If empty, it is shown in the name-only list. Prefer a 4:3 image.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Select the weather applied to event pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weather-settings".
 */
export interface WeatherSetting {
  id: number;
  /**
   * Event pages display schedule times for the selected weather.
   */
  weather: 'sunny' | 'rainy';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top-page_select".
 */
export interface TopPageSelect<T extends boolean = true> {
  pickups?:
    | T
    | {
        image?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page_select".
 */
export interface EventsPageSelect<T extends boolean = true> {
  programItems?:
    | T
    | {
        program?: T;
        programLabel?: T;
        id?: T;
      };
  exhibitionItems?:
    | T
    | {
        program?: T;
        programLabel?: T;
        id?: T;
      };
  foodItems?:
    | T
    | {
        program?: T;
        programLabel?: T;
        id?: T;
      };
  goodsItems?:
    | T
    | {
        program?: T;
        programLabel?: T;
        id?: T;
      };
  corporateItems?:
    | T
    | {
        program?: T;
        programLabel?: T;
        id?: T;
      };
  visibleTags?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors-page_select".
 */
export interface SponsorsPageSelect<T extends boolean = true> {
  thanksMessage?: T;
  sponsors?:
    | T
    | {
        companyName?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weather-settings_select".
 */
export interface WeatherSettingsSelect<T extends boolean = true> {
  weather?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}